GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [TMS].[TCS_USER](
	[USERID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [int] NOT NULL,
	[PINCODE] [nvarchar](50) NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[TDMINITIALS] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[MOBILE] [nvarchar](50) NULL,
	[DEPARTMENT] [nvarchar](50) NULL,
	[WORK] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[INFO] [nvarchar](50) NULL,
	[INFO2] [nvarchar](50) NULL,
 CONSTRAINT [PK_tcs_user] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [PIN_tcs_user] UNIQUE NONCLUSTERED 
(
	[PINCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_tcs_user] UNIQUE NONCLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
